@url = http://localhost:8000/api
###
@evento = {"materia": 11, "responsable": "11", "ambiente": "11", "periodo": "11", "tipo": "laboratorio", "nivel": "docente", "day": "3", "startTime": "15:00", "endTime": "19:00", "paralelo": "A" };
###
GET {{url}}
###
http://localhost:8000/api/clases?estado=false
###
GET {{url}}/ambientes?tipo=laboratorio
# Crear una clase
###
POST {{url}}/clases
Content-Type: application/json

{
    "materia": 4, 
    "responsable": 414, 
    "ambiente": 6, 
    "periodo": 3, 
    "tipo": "laboratorio", 
    "nivel": "docente", 
    "day": 3, 
    "startTime": "15:00", 
    "endTime": "19:00", 
    "paralelo": "A" 
}

###
# Editar una clase
###
Put {{url}}/clases/167
Content-Type: application/json

{
    "materia": 4, 
    "responsable": 414, 
    "ambiente": 7, 
    "periodo": 3, 
    "tipo": "laboratorio", 
    "nivel": "docente", 
    "day": 4, 
    "startTime": "15:00", 
    "endTime": "19:00", 
    "paralelo": "B" 
}

###
#Eliminar
DELETE {{url}}/clases/170

###
get {{url}}/clases?estado=false







# ejemplo de uso de variables
###
@urlprueba = https://jsonplaceholder.typicode.com/posts 
###

# @name respuesta
POST {{ urlprueba}}
Content-Type: application/json

{
    "title": "joel",
    "body"  : "bar",
    "userId": 72
}

###
@id ={{ respuesta.response.body.$.userId }}

###
GET {{urlprueba}}/{{id}}