@url = http://localhost:8000/api
###
@evento = {"materia": 11, "responsable": "11", "ambiente": "11", "periodo": "11", "tipo": "laboratorio", "nivel": "docente", "day": "3", "startTime": "15:00", "endTime": "19:00", "paralelo": "A" };
###
GET {{url}}
###
http://localhost:8000/api/clases?estado=false
###
##  AMBIENTE
###
GET {{url}}/ambientes?tipo=laboratorio
###
# ambientes usados
get {{url}}/now?index=ambientes


##  CLASE 
# Crear una clase
###
POST {{url}}/clases
Content-Type: application/json

{
    "materia": 4, 
    "responsable": 414, 
    "ambiente": 6, 
    "periodo": 3, 
    "tipo": "laboratorio", 
    "nivel": "docente", 
    "day": 3, 
    "startTime": "15:00", 
    "endTime": "19:00", 
    "paralelo": "A" 
}
###

###
# Editar una clase
###
Put {{url}}/clases/167
Content-Type: application/json

{
    "materia": 4, 
    "responsable": 414, 
    "ambiente": 7, 
    "periodo": 3, 
    "tipo": "laboratorio", 
    "nivel": "docente", 
    "day": 4, 
    "startTime": "15:00", 
    "endTime": "19:00", 
    "paralelo": "B" 
}

###
#Eliminar
DELETE {{url}}/clases/170

###
get {{url}}/clases?estado=false
## RESPONSABLES
###
Put {{url}}/responsables/1
###
delete {{url}}/responsables/1
# USERS #
###
get {{url}}/users
###
post {{url}}/users

Content-Type: application/json

{
    "name": 4, 
    "responsable": 414, 
    "ambiente": 7, 
    "periodo": 3, 
    "tipo": "laboratorio", 
    "nivel": "docente", 
    "day": 4, 
    "startTime": "15:00", 
    "endTime": "19:00", 
    "paralelo": "B" 
}
###
put {{url}}/users/28
{
    "name": 4, 
    "responsable": 414, 
    "ambiente": 7, 
    "periodo": 3, 
    "tipo": "laboratorio", 
    "nivel": "docente", 
    "day": 4, 
    "startTime": "15:00", 
    "endTime": "19:00", 
    "paralelo": "B" 
}
###
delete {{url}}/users/28

## PENSUM
###
POST {{url}}/pensums
###
put {{url}}/pensums/1
###
delete {{url}}/pensums/3
## MENCION
###
post {{url}}/menciones
###
put {{url}}/menciones/15
###
delete {{url}}/menciones/15

## Clases
###
get {{url}}/now?index=ambientes


















# ejemplo de uso de variables
###
@urlprueba = https://jsonplaceholder.typicode.com/posts 
###

# @name respuesta
POST {{ urlprueba}}
Content-Type: application/json

{
    "title": "joel",
    "body"  : "bar",
    "userId": 72
}

###
@id ={{ respuesta.response.body.$.userId }}

###
GET {{urlprueba}}/{{id}}